import dubaiProjImg from '../../assets/Projects/_Processed to 1.53 ratio/Dubai-Mall.jpg';
import nbaProjImg from '../../assets/Projects/_Processed to 1.53 ratio/NBA-Logo_Thumb.jpg';
import ydlmProjImg from '../../assets/Projects/_Processed to 1.53 ratio/Sardine-Run-02.jpg';
import ydlm2ProjImg from '../../assets/Projects/Sardine-Run-01.jpg';
import courchevelProjImg from '../../assets/Projects/_Processed to 1.53 ratio/courchevel-night-1-721x471.jpg';
import fifaProjImg from '../../assets/Projects/_Processed to 1.53 ratio/FIFA-trophy-thumb-Benjamin-Proulx-Mathers-Christian-Lagueux-YUL-MUSIC-Montreal-Composer.jpg';
import astanaProjImg from '../../assets/Projects/_Processed to 1.53 ratio/Astana_Christian-Lagueux_Benjamin-Proulx-Mathers_YUL-MUSIC_Composer_Montréal-721x471.jpg';
import laxProjImg from '../../assets/Projects/_Processed to 1.53 ratio/LAX-2.jpg';
import mjProjImg from '../../assets/Projects/Michael-Jackson-The-Immortal-World-Tour-by-Cirque-du-Soleil_YUL-MUSIC-Christian-Lagueux-Benjamin-Proulx-Mathers-Sébastien-Laurendeau.jpg';

export const projectsData = [
  {
    id: 101,
    title: 'YUL MUSIC / Productions J',
    subtitle:
      'YUL MUSIC - Mario Cyr, conference "Les yeux de la mer" - Mario Cyr is an internationally renowned expedition leader for Arctic and Antarctic missions, a cold-water diving expert and a world-class cinematographer.',
    detailedSubtitle:
      'YUL MUSIC - Mario Cyr, conference "Les yeux de la mer" - Mario Cyr is an internationally renowned expedition leader for Arctic and Antarctic missions, a cold-water diving expert and a world-class cinematographer. He has participated in more than 150 films for broadcasters such as National Geographic, Discovery Channel, the BBC, IMAX 3D, Disney Productions, the CBC and David Suzuki, la Société Cousteau, France 2, Arte and NHK Japan.',
    categoriesText:
      'Music composition - Music arrangements - MIDI orchestration - Music editing - Audio restoration - Audio montage - Sound design - Music supervision - Preproduction - Postproduction - Mix',
    bgImg: ydlmProjImg,
    // possible types: img, video, others?
    extraMedia: [{ type: 'img', data: ydlm2ProjImg }],
  },
  {
    id: 102,
    title: 'YUL MUSIC / NBA',
    subtitle:
      'YUL MUSIC in Toronto - Cirque du Soleil 45 Degrees / The 2016 NBA All-Star Pregame Show, televised in over 200 countries',
    categoriesText:
      'Music composition - MIDI orchestration - Music arrangements - Music editing - Music supervision - Sound design - Voice Over - Preproduction - Postproduction - Mix',
    bgImg: nbaProjImg,
    extraMedia: [
      {
        type: 'video',
        data: { url: 'https://player.vimeo.com/video/157210250' },
      },
    ],
  },
  {
    id: 103,
    title: 'YUL MUSIC / Cirque du Soleil',
    subtitle:
      "YUL MUSIC in Courchevel - A custom made Cirque du Soleil show, also starring Christina Aguilera and Monégasque superchef Alain Ducasse for Victor Pinchuk's 50th Birthday party",
    year: '2020',
    bgImg: courchevelProjImg,
  },
  {
    id: 104,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: dubaiProjImg,
  },
  {
    id: 105,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: fifaProjImg,
  },
  {
    id: 106,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: astanaProjImg,
  },
  {
    id: 107,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: laxProjImg,
  },
  {
    id: 108,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: dubaiProjImg,
  },
  {
    id: 109,
    title: 'Project Title',
    subtitle: 'Subtitle',
    year: '2020',
    bgImg: mjProjImg,
  },
  // {
  //   id: 6,
  //   title: 'Magnum Pleasure Store',
  //   subtitle: 'Project Subtitle 6',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 7,
  //   title: 'NBA',
  //   subtitle: 'Project Subtitle 7',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 8,
  //   title: 'Infinity',
  //   subtitle: 'Project Subtitle 8',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 9,
  //   title: 'Sales Force',
  //   subtitle: 'Project Subtitle 9',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 10,
  //   title: 'Biion Footwear',
  //   subtitle: 'Project Subtitle 10',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 11,
  //   title: 'Tim Hortons',
  //   subtitle: 'Project Subtitle 11',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 12,
  //   title: 'Sid Lee',
  //   subtitle: 'Project Subtitle 12',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 13,
  //   title: 'Mobilia',
  //   subtitle: 'Project Subtitle 13',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 14,
  //   title: 'Productions Déferlantes',
  //   subtitle: 'Project Subtitle 14',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 15,
  //   title: 'SAP',
  //   subtitle: 'Project Subtitle 15',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 16,
  //   title: 'Canadian Olympic Comittee',
  //   subtitle: 'Project Subtitle 16',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 17,
  //   title: 'Michael Jackson',
  //   subtitle: 'Project Subtitle 17',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 18,
  //   title: 'Iris',
  //   subtitle: 'Project Subtitle 18',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 19,
  //   title: 'Dubaï Mall',
  //   subtitle: 'Project Subtitle 19',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 20,
  //   title: 'FIFA World Cup',
  //   subtitle: 'Project Subtitle 20',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 21,
  //   title: 'Mary Poppins',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 22,
  //   title: 'Bombardier Global 7000',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 23,
  //   title: 'World Economic Forum',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 24,
  //   title: 'Glade in NYC',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 25,
  //   title: 'One Drop Microsoft App',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 26,
  //   title: 'Beijing Parkview Green',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 27,
  //   title: 'LAX Airport',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 28,
  //   title: 'SITU Studio NYC',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 29,
  //   title: 'Mater Natura',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 30,
  //   title: 'Storia',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 31,
  //   title: 'Vision - Andorra',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 32,
  //   title: 'Astana City Celebration',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 33,
  //   title: "Victor Pinchuk's 50th Birthday party",
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 34,
  //   title: 'Minera Santa-María 150th Anniversary',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 35,
  //   title: 'Charlottetown Summerfest',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 36,
  //   title: 'Bravura - Mumbai',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 37,
  //   title: 'Nucléus, MTL en lumière',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 38,
  //   title: 'One Night for One Drop',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 39,
  //   title: 'One Drop',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 40,
  //   title: 'One Drop Microsoft',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 41,
  //   title: 'Montréal en fête',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 42,
  //   title: "Hotels et restos d'exception",
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 43,
  //   title: 'En Pays Maya',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 44,
  //   title: 'Montréal Canadiens',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 45,
  //   title: 'Do Art Foundation',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 46,
  //   title: 'World Economic Forum',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
  // {
  //   id: 47,
  //   title: 'Barila & Compagnie',
  //   subtitle: 'Project Subtitle',
  //   year: '2020',
  //   bgImg: dubaiProjImg,
  // },
];
