import serviceEventBg from '../../assets/Services/eventsBg-1200px-40p.jpg';
import imgBiion from '../../assets/Projects/Biion-2-Benjamin-Proulx-Mathers-Christian-Lagueux-YUL-MUSIC-Montreal-Composer.jpg';
import imgDubaiMall from '../../assets/Projects/Dubai-Mall.jpg';
import imgParkView from '../../assets/Projects/Parkview-Thumb-2.jpg';
import imgNBA from '../../assets/Projects/NBA-Logo_Thumb.jpg';
import imgLax from '../../assets/Projects/LAX-Benjamin-Proulx-Mathers-Christian-Lagueux-YUL-MUSIC-Montreal-Composer.jpg';
import imgMagnum from '../../assets/Projects/Magnum-Logo-Benjamin-Proulx-Mathers-Christian-Lagueux-YUL-MUSIC-Montreal-Composer.jpg';

export const projectsData = [
  {
    id: 101,
    title: 'Bocca - Monaco',
    subtitle: 'Project Subtitle 1',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 102,
    title: 'AliBaba ?',
    subtitle: 'Project Subtitle 1',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 103,
    title: 'Autre show monaco avec Hassan',
    subtitle: 'Project Subtitle 1',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 104,
    title: 'Sorry G pas rescapé les projets des 2-3 dernières années',
    subtitle: 'Va falloir tu me refasses une liste',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 105,
    title: 'Les yeux de la mer',
    subtitle: 'Project Subtitle 1',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 2,
    title: 'Skoda',
    subtitle: 'Project Subtitle 2',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 3,
    title: 'Texas Pacific Group',
    subtitle: 'Project Subtitle 3',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 4,
    title: 'Songcheng',
    subtitle: 'Project Subtitle 4',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 5,
    title: 'Bulgari',
    subtitle: 'Project Subtitle 5',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 6,
    title: 'Magnum Pleasure Store',
    subtitle: 'Project Subtitle 6',
    year: '2020',
    bgImg: imgMagnum,
  },
  {
    id: 7,
    title: 'NBA',
    subtitle: 'Project Subtitle 7',
    year: '2020',
    bgImg: imgNBA,
  },
  {
    id: 8,
    title: 'Infinity',
    subtitle: 'Project Subtitle 8',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 9,
    title: 'Sales Force',
    subtitle: 'Project Subtitle 9',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 10,
    title: 'Biion Footwear',
    subtitle: 'Project Subtitle 10',
    year: '2020',
    bgImg: imgBiion,
  },
  {
    id: 11,
    title: 'Tim Hortons',
    subtitle: 'Project Subtitle 11',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 12,
    title: 'Sid Lee',
    subtitle: 'Project Subtitle 12',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 13,
    title: 'Mobilia',
    subtitle: 'Project Subtitle 13',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 14,
    title: 'Productions Déferlantes',
    subtitle: 'Project Subtitle 14',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 15,
    title: 'SAP',
    subtitle: 'Project Subtitle 15',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 16,
    title: 'Canadian Olympic Comittee',
    subtitle: 'Project Subtitle 16',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 17,
    title: 'Michael Jackson',
    subtitle: 'Project Subtitle 17',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 18,
    title: 'Iris',
    subtitle: 'Project Subtitle 18',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 19,
    title: 'Dubaï Mall',
    subtitle: 'Project Subtitle 19',
    year: '2020',
    bgImg: imgDubaiMall,
  },
  {
    id: 20,
    title: 'FIFA World Cup',
    subtitle: 'Project Subtitle 20',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 21,
    title: 'Mary Poppins',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 22,
    title: 'Bombardier Global 7000',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 23,
    title: 'World Economic Forum',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 24,
    title: 'Glade in NYC',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 25,
    title: 'One Drop Microsoft App',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 26,
    title: 'Beijing Parkview Green',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: imgParkView,
  },
  {
    id: 27,
    title: 'LAX Airport',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: imgLax,
  },
  {
    id: 28,
    title: 'SITU Studio NYC',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 29,
    title: 'Mater Natura',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 30,
    title: 'Storia',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 31,
    title: 'Vision - Andorra',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 32,
    title: 'Astana City Celebration',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 33,
    title: "Victor Pinchuk's 50th Birthday party",
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 34,
    title: 'Minera Santa-María 150th Anniversary',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 35,
    title: 'Charlottetown Summerfest',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 36,
    title: 'Bravura - Mumbai',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 37,
    title: 'Nucléus, MTL en lumière',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 38,
    title: 'One Night for One Drop',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 39,
    title: 'One Drop',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 40,
    title: 'One Drop Microsoft',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 41,
    title: 'Montréal en fête',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 42,
    title: "Hotels et restos d'exception",
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 43,
    title: 'En Pays Maya',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 44,
    title: 'Montréal Canadiens',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 45,
    title: 'Do Art Foundation',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 46,
    title: 'World Economic Forum',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
  {
    id: 47,
    title: 'Barila & Compagnie',
    subtitle: 'Project Subtitle',
    year: '2020',
    bgImg: serviceEventBg,
  },
];
